---
title: "graded lab dplyr"
author: "Puwen WEN"
format: html
editor: visual
---

# Simple Analysis
## Question 1 Data Import


```{r}
#| message: false
here::i_am("grades-eval.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(dplyr)

```

You can add options to executable code like this

```{r}
#| message: false
grades <- vroom(here("grades.csv"))
```
## Question 2

The dataset contains 48083 grades.

## Question 3
```{r}

num_students <- grades |>
  distinct(`id`)|>
  count(name = "num_students")
num_students
```
The number of students is 719.

## Question 4

```{r}

students <- grades |>
  distinct(`id`,.keep_all = TRUE)|>
  select(`group`,`id`)

students |>
  slice_tail(n=5) |>
  knitr::kable()


```

## Question 5
```{r}

students_per_group <- students |>
  count(group)
students_per_group

ggplot(students_per_group, aes(x = group, y = n)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Number of Students per Group",
       x = "Group",
       y = "Number of Students") +
  theme_minimal()

```

## Question 6

```{r}

average_grades <- grades |>
  filter(`course` == "History and Civilization of Southeast Asia")|>
  group_by(`group`) |>
  summarize(avg_history_civ_se_asia = mean(`grade`, na.rm = TRUE))
average_grades

ggplot(average_grades, aes(x = `group`, y = avg_history_civ_se_asia)) +
  geom_col(fill = "steelblue") +
  labs(title = "Average Grade in History and Civilization of Southeast Asia by Group",
       x = "Group",
       y = "Average Grade") +
  theme_minimal()

```
## Question 7

```{r}


average_grades_by_course_second_semester <- grades |>
  filter(`semester` == 2)|>
  group_by(`course`) |>
  summarize(avg_score = mean(`grade`, na.rm = TRUE))
average_grades_by_course_second_semester

average_grades_by_group_second_semester <- grades |>
  filter(`semester` == 2)|>
  group_by(`group`) |>
  summarize(avg_score = mean(`grade`, na.rm = TRUE))
average_grades_by_group_second_semester


ggplot(average_grades_by_course_second_semester, aes(x = reorder(course, avg_score), y = avg_score)) +
  geom_col(fill = "cornflowerblue") +
  labs(title = "Average Grades by Course (Second Semester)",
       x = "Course",
       y = "Average Grade") +
  coord_flip() +
  theme_minimal()

ggplot(average_grades_by_group_second_semester, aes(x = group, y = avg_score)) +
  geom_col(fill = "lightseagreen") +
  labs(title = "Average Grades by Group (Second Semester)",
       x = "Group",
       y = "Average Grade") +
  theme_minimal()

```
# Attendance Analysis

## Question 8

```{r}

num_grades <- grades|>
  group_by(`id`)|>
  mutate(num_grades = n())|>
  select(`group`,`id`,`num_grades`)|>
  distinct(id, .keep_all = TRUE)

num_grades |>
  slice_tail(n=5) |>
  knitr::kable()


```

## Question 9

```{r}

grades_arch_sculp <- grades|>
  filter(`course` == "Architecture and Sculpture")|>
  group_by(`id`)|>
  mutate(num_grades = n())|>
  select(`group`,`id`,`num_grades`)|>
  distinct(`id`, .keep_all = TRUE)
grades_arch_sculp|>
  slice_tail(n=5)|>
  knitr::kable()

```








The `echo: false` option disables the printing of code (only output is displayed).
